name: Components action

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: "Lint and test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test

#   publish:
#     name: "Publish to NPM"
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Check version changes
#         uses: EndBug/version-check@v2
#         id: check

#       - name: Version update detected
#         if: steps.check.outputs.changed == 'true'
#         run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

#       - name: Set up Node.js for NPM
#         if: steps.check.outputs.changed == 'true'
#         uses: actions/setup-node@v2
#         with:
#           registry-url: "https://registry.npmjs.org"
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - run: npm ci
#       - run: npm publish
